/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg3rdfinalproject;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author A315
 */
public class MinimalistCustomCake extends javax.swing.JFrame {

    /**
     * Creates new form MinimalistCustomCake
     */
    private BeaPOS beaPOSParent;
    private String selectedSize = null;
    private int selectedPrice = 0;
    private int selectedQuantity = 0;
    
    int miniQty = 0;
    int miniBasePrice = 0;
    public MinimalistCustomCake(BeaPOS beaPOSparent) {
        initComponents();
        
        
        this.beaPOSParent = beaPOSparent;
        //custom icing cake 
        ActionListener sizeBtnListener = e -> {
            JToggleButton src = (JToggleButton) e.getSource();
            // Deselect all
            btn4x2Minimalist.setSelected(false);
            btn5x2MinimalistCake.setSelected(false);
            btn5x3MinimalistCake.setSelected(false);
            btn6x2MinimalistCake.setSelected(false);
            btn7x2MinimalistCake.setSelected(false);
            btn8x2MinimalistCake.setSelected(false);
            btn8x4MinimalistCake.setSelected(false);
            btn9x4MinimalistCake.setSelected(false);
            
            // Select only this
            src.setSelected(true);
            // Set size and price
            if (src == btn4x2Minimalist) {
                selectedSize = "4 x 2\"";
                selectedPrice = 250;
            } else if (src == btn5x2MinimalistCake) {
                selectedSize = "5 x 2\"";
                selectedPrice = 400;
            } else if (src == btn5x3MinimalistCake) {
                selectedSize = "5 x 3\"";
                selectedPrice = 550;
            } else if (src == btn6x2MinimalistCake) {
                selectedSize = "6 x 2\"";
                selectedPrice = 649;
            } else if (src == btn7x2MinimalistCake) {
                selectedSize = "7 x 2\"";
                selectedPrice = 849;
            } else if (src == btn8x2MinimalistCake) {
                selectedSize = "8 x 2\"";
                selectedPrice = 949;
            } else if (src == btn8x4MinimalistCake) {
                selectedSize = "8 x 4\"";
                selectedPrice = 1200;
            } else if (src == btn9x4MinimalistCake){
                selectedSize = "9 x 4\"";
                selectedPrice = 1700;
            }
            updatePriceDisplay();
        };
         
        
            btn4x2Minimalist.addActionListener(sizeBtnListener);
            btn5x2MinimalistCake.addActionListener(sizeBtnListener);
            btn5x3MinimalistCake.addActionListener(sizeBtnListener);
            btn6x2MinimalistCake.addActionListener(sizeBtnListener);
            btn7x2MinimalistCake.addActionListener(sizeBtnListener);
            btn8x2MinimalistCake.addActionListener(sizeBtnListener);
            btn8x4MinimalistCake.addActionListener(sizeBtnListener);
            btn9x4MinimalistCake.addActionListener(sizeBtnListener);
            
            
        btnPlusIcingCake.addActionListener(e -> {
            selectedQuantity++;
            lbzeroQty.setText(String.valueOf(selectedQuantity));
            updatePriceDisplay();
        });

        btnMinusIcingCake.addActionListener(e -> {
            if (selectedQuantity > 0) {
                selectedQuantity--;
                lbzeroQty.setText(String.valueOf(selectedQuantity));
                updatePriceDisplay();
            }
        });
        
        
        
        confirmButton.addActionListener(e -> {
    if (selectedSize == null || selectedQuantity <= 0) {
        JOptionPane.showMessageDialog(this, "Please select a size and quantity.");
        return;
    }
    if (beaPOSParent != null) {
        beaPOSParent.addMinimalistCustomCakeToBill(selectedSize, selectedQuantity, selectedPrice);
    }
    this.dispose();
});

        // Initialize display
        lbzeroQty.setText("0");
        updatePriceDisplay();
    
    
    }
        
    
    private void updatePriceDisplay() {
        customCakePrice.setText("Php: " + (selectedPrice * selectedQuantity) + ".00");
    }
    private void updateCustomMinimalistCakePrice(){
        int total = (miniBasePrice) * miniQty;
        customCakePrice.setText("Php: " + total + ".00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        btn4x2Minimalist = new javax.swing.JToggleButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        btn5x2MinimalistCake = new javax.swing.JToggleButton();
        btn5x3MinimalistCake = new javax.swing.JToggleButton();
        btn6x2MinimalistCake = new javax.swing.JToggleButton();
        btn7x2MinimalistCake = new javax.swing.JToggleButton();
        btn8x2MinimalistCake = new javax.swing.JToggleButton();
        btn8x4MinimalistCake = new javax.swing.JToggleButton();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        btn9x4MinimalistCake = new javax.swing.JToggleButton();
        jLabel108 = new javax.swing.JLabel();
        btnMinusIcingCake = new javax.swing.JButton();
        btnPlusIcingCake = new javax.swing.JButton();
        lbzeroQty = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        customCakePrice = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        lb1700MinimalistCake = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        lb1200MinimalistCake = new javax.swing.JLabel();
        lb949MinimalistCake = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        lb849MinimalistCake = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        lb649MinimalistCake = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        lb550MinimalistCake = new javax.swing.JLabel();
        lb400MinimalistCake = new javax.swing.JLabel();
        lb250MinimalistCake = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel13.setBackground(new java.awt.Color(44, 204, 98));

        jPanel12.setBackground(new java.awt.Color(225, 135, 44));

        jPanel11.setBackground(new java.awt.Color(255, 255, 153));
        jPanel11.setForeground(new java.awt.Color(225, 135, 44));

        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BeA D' Lites.1png.png"))); // NOI18N

        jLabel83.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(225, 135, 44));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Custom Minimalist Cake");

        btn4x2Minimalist.setBackground(new java.awt.Color(255, 255, 153));
        btn4x2Minimalist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4x2Minimalist.setForeground(new java.awt.Color(225, 135, 44));
        btn4x2Minimalist.setText("4 x 2\"");

        jLabel84.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(225, 135, 44));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("Size");

        jLabel85.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(225, 135, 44));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("Price");

        jLabel86.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(225, 135, 44));
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("&");

        btn5x2MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn5x2MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5x2MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn5x2MinimalistCake.setText("5 x 2\"");

        btn5x3MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn5x3MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5x3MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn5x3MinimalistCake.setText("5 x 3\"");

        btn6x2MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn6x2MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn6x2MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn6x2MinimalistCake.setText("6 x 2\"");

        btn7x2MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn7x2MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn7x2MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn7x2MinimalistCake.setText("7 x 2\"");

        btn8x2MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn8x2MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn8x2MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn8x2MinimalistCake.setText("8 x 2\"");

        btn8x4MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn8x4MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn8x4MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn8x4MinimalistCake.setText("8 x 4\"");

        jLabel87.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(225, 135, 44));
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("-");

        jLabel88.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(225, 135, 44));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("-");

        jLabel89.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(225, 135, 44));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("-");

        jLabel90.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(225, 135, 44));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("-");

        jLabel91.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(225, 135, 44));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("-");

        jLabel92.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(225, 135, 44));
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("-");

        jLabel93.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(225, 135, 44));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("-");

        btn9x4MinimalistCake.setBackground(new java.awt.Color(255, 255, 153));
        btn9x4MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn9x4MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        btn9x4MinimalistCake.setText("9 x  4\"");

        jLabel108.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(225, 135, 44));
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("-");

        btnMinusIcingCake.setBackground(new java.awt.Color(255, 204, 102));
        btnMinusIcingCake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMinusIcingCake.setForeground(new java.awt.Color(225, 135, 44));
        btnMinusIcingCake.setText("-");
        btnMinusIcingCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusIcingCakeActionPerformed(evt);
            }
        });

        btnPlusIcingCake.setBackground(new java.awt.Color(255, 204, 102));
        btnPlusIcingCake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlusIcingCake.setForeground(new java.awt.Color(225, 135, 44));
        btnPlusIcingCake.setText("+");
        btnPlusIcingCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusIcingCakeActionPerformed(evt);
            }
        });

        lbzeroQty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbzeroQty.setForeground(new java.awt.Color(225, 135, 44));
        lbzeroQty.setText("0");

        jPanel2.setBackground(new java.awt.Color(225, 135, 44));

        customCakePrice.setBackground(new java.awt.Color(255, 204, 102));
        customCakePrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customCakePrice.setForeground(new java.awt.Color(255, 255, 153));
        customCakePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customCakePrice.setText("Php: 0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customCakePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(customCakePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        confirmButton.setBackground(new java.awt.Color(255, 204, 102));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(225, 135, 44));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        lb1700MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb1700MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb1700MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1700MinimalistCake.setText("1,700");

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        lb1200MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb1200MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb1200MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1200MinimalistCake.setText("1,200");

        lb949MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb949MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb949MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb949MinimalistCake.setText("949");

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        lb849MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb849MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb849MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb849MinimalistCake.setText("849");

        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        lb649MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb649MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb649MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb649MinimalistCake.setText("649");

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        lb550MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb550MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb550MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb550MinimalistCake.setText("550");

        lb400MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb400MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb400MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb400MinimalistCake.setText("400");

        lb250MinimalistCake.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb250MinimalistCake.setForeground(new java.awt.Color(225, 135, 44));
        lb250MinimalistCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb250MinimalistCake.setText("250");

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/philippine-peso.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel94)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb250MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel100)
                                    .addComponent(jLabel97)
                                    .addComponent(jLabel98)
                                    .addComponent(jLabel96))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb949MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb649MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb550MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb400MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel101)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb1200MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel99)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb849MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel109)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb1700MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb1700MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb250MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel96, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb400MinimalistCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb550MinimalistCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb649MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb849MinimalistCake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel99, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb949MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb1200MinimalistCake, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn8x4MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn8x2MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn7x2MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn6x2MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn5x3MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn5x2MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn4x2Minimalist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn9x4MinimalistCake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMinusIcingCake)
                                .addGap(18, 18, 18)
                                .addComponent(lbzeroQty)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnPlusIcingCake)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(confirmButton)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4x2Minimalist)
                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn5x2MinimalistCake)
                            .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn5x3MinimalistCake)
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn6x2MinimalistCake)
                            .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7x2MinimalistCake)
                            .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn8x2MinimalistCake)
                            .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel93, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8x4MinimalistCake, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn9x4MinimalistCake)
                            .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinusIcingCake)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPlusIcingCake)
                                .addComponent(lbzeroQty))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinusIcingCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusIcingCakeActionPerformed
        if(miniQty>0){
            miniQty--;
            lbzeroQty.setText(String.valueOf(miniQty));
            updateCustomMinimalistCakePrice();
        }
    }//GEN-LAST:event_btnMinusIcingCakeActionPerformed

    private void btnPlusIcingCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusIcingCakeActionPerformed
            miniQty++;
            lbzeroQty.setText(String.valueOf(miniQty));
            updateCustomMinimalistCakePrice();
    }//GEN-LAST:event_btnPlusIcingCakeActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinimalistCustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinimalistCustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinimalistCustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinimalistCustomCake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BeaPOS BeaPOS = null;
                new MinimalistCustomCake(BeaPOS).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn4x2Minimalist;
    private javax.swing.JToggleButton btn5x2MinimalistCake;
    private javax.swing.JToggleButton btn5x3MinimalistCake;
    private javax.swing.JToggleButton btn6x2MinimalistCake;
    private javax.swing.JToggleButton btn7x2MinimalistCake;
    private javax.swing.JToggleButton btn8x2MinimalistCake;
    private javax.swing.JToggleButton btn8x4MinimalistCake;
    private javax.swing.JToggleButton btn9x4MinimalistCake;
    private javax.swing.JButton btnMinusIcingCake;
    private javax.swing.JButton btnPlusIcingCake;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel customCakePrice;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb1200MinimalistCake;
    private javax.swing.JLabel lb1700MinimalistCake;
    private javax.swing.JLabel lb250MinimalistCake;
    private javax.swing.JLabel lb400MinimalistCake;
    private javax.swing.JLabel lb550MinimalistCake;
    private javax.swing.JLabel lb649MinimalistCake;
    private javax.swing.JLabel lb849MinimalistCake;
    private javax.swing.JLabel lb949MinimalistCake;
    private javax.swing.JLabel lbzeroQty;
    // End of variables declaration//GEN-END:variables
}
