/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg3rdfinalproject;

import javax.swing.JButton;

/**
 *
 * @author Lynch
 */
public class ProductPanel extends javax.swing.JFrame {

    /**
     * Creates new form ProductPanel
     */
     private BeaPOS parent;

    // Product info fields
    private String productName;
    private String[] sizes;
    private String[] toppings;
    private int quantity = 1;

    // Selected options
    private String selectedSize = "";
    private String selectedToppings = "";
    
    
     public ProductPanel() {
        super();
        initComponents();
    }
    
     public ProductPanel(BeaPOS parent, String productName, String[] sizes, String[] toppings) {
        this.parent = parent;
        this.productName = productName;
        this.sizes = sizes;
        this.toppings = toppings;
        initComponents(); // Must be called after setting fields used in display
        setLocationRelativeTo(null);
        setUpProductDisplay();
        setupToppings(toppings);
        
    }
    
    
    
    private void setUpProductDisplay() {
    ProductLabel.setText(productName);

    sizeButton.setVisible(sizes.length > 0);
    sizeButton.setText(sizes.length > 0 ? sizes[0] : "");
    sizeButton2.setVisible(sizes.length > 1);
    sizeButton2.setText(sizes.length > 1 ? sizes[1] : "");
    sizeButton3.setVisible(sizes.length > 2);
    sizeButton3.setText(sizes.length > 2 ? sizes[2] : "");
    selectedSize = sizes.length > 0 ? sizes[0] : "";

    // Set toppings buttons visibility and text
    toppingsButton.setVisible(toppings.length > 0);
    toppingsButton.setText(toppings.length > 0 ? toppings[0] : "");
    toppingsButton1.setVisible(toppings.length > 1);
    toppingsButton1.setText(toppings.length > 1 ? toppings[1] : "");
    toppingsButton2.setVisible(toppings.length > 2);
    toppingsButton2.setText(toppings.length > 2 ? toppings[2] : "");
    toppingsButton3.setVisible(toppings.length > 3);
    toppingsButton3.setText(toppings.length > 3 ? toppings[3] : "");

    quantityLabel.setText(String.valueOf(quantity));
    }
     
    private void setupToppings(String[] toppings) {
    toppingsPanel.removeAll(); // Remove any previous buttons
    

    for (String topping : toppings) {
        JButton btn = new JButton();
        btn.setText(topping); // Or setText("") if you only want the icon
        // Set icon if 
        // btn.setIcon(getToppingIcon(topping));
        btn.addActionListener(e -> {
            selectedToppings = topping; // Store selected topping
            // If you want to allow multiple toppings, append/add to a list instead
        });
        toppingsPanel.add(btn);
        // For radio buttons (single choice), use JRadioButton instead and add to toppingsGroup
    }

    toppingsPanel.revalidate();
    toppingsPanel.repaint();
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        imageOfProductLabel = new javax.swing.JLabel();
        ProductLabel = new javax.swing.JLabel();
        sizeButton3 = new javax.swing.JToggleButton();
        sizeButton2 = new javax.swing.JToggleButton();
        sizeButton = new javax.swing.JToggleButton();
        jLabel72 = new javax.swing.JLabel();
        doneButton = new javax.swing.JToggleButton();
        productQuantityMinusBtn = new javax.swing.JButton();
        productQuantityPlusButton = new javax.swing.JButton();
        quantityLabel = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JToggleButton();
        toppingsPanel = new javax.swing.JPanel();
        toppingsButton = new javax.swing.JToggleButton();
        toppingsButton1 = new javax.swing.JToggleButton();
        toppingsButton2 = new javax.swing.JToggleButton();
        toppingsButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 204, 98));

        jPanel2.setBackground(new java.awt.Color(225, 135, 44));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));

        imageOfProductLabel.setBackground(new java.awt.Color(225, 135, 44));
        imageOfProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageOfProductLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mango bravo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageOfProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageOfProductLabel)
                .addContainerGap())
        );

        ProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProductLabel.setForeground(new java.awt.Color(225, 135, 44));
        ProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductLabel.setText("Product Label");

        sizeButton3.setBackground(new java.awt.Color(255, 255, 153));
        sizeButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sizeButton3.setForeground(new java.awt.Color(225, 135, 44));
        sizeButton3.setText("6 x 2\"");
        sizeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeButton3ActionPerformed(evt);
            }
        });

        sizeButton2.setBackground(new java.awt.Color(255, 255, 153));
        sizeButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sizeButton2.setForeground(new java.awt.Color(225, 135, 44));
        sizeButton2.setText("5 x 2\"");
        sizeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeButton2ActionPerformed(evt);
            }
        });

        sizeButton.setBackground(new java.awt.Color(255, 255, 153));
        sizeButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        sizeButton.setForeground(new java.awt.Color(225, 135, 44));
        sizeButton.setText("4 x 2\"");
        sizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeButtonActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(225, 135, 44));
        jLabel72.setText("Toppings:");

        doneButton.setBackground(new java.awt.Color(255, 255, 153));
        doneButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        doneButton.setForeground(new java.awt.Color(225, 135, 44));
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        productQuantityMinusBtn.setBackground(new java.awt.Color(255, 204, 102));
        productQuantityMinusBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        productQuantityMinusBtn.setForeground(new java.awt.Color(225, 135, 44));
        productQuantityMinusBtn.setText("-");
        productQuantityMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityMinusBtnActionPerformed(evt);
            }
        });

        productQuantityPlusButton.setBackground(new java.awt.Color(255, 204, 102));
        productQuantityPlusButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        productQuantityPlusButton.setForeground(new java.awt.Color(225, 135, 44));
        productQuantityPlusButton.setText("+");
        productQuantityPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityPlusButtonActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(225, 135, 44));
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityLabel.setText("0");

        jLabel73.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(225, 135, 44));
        jLabel73.setText("Sizes:");

        jLabel74.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(225, 135, 44));
        jLabel74.setText("Quantity:");

        CancelButton.setBackground(new java.awt.Color(255, 255, 153));
        CancelButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(225, 135, 44));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        toppingsPanel.setBackground(new java.awt.Color(255, 204, 102));

        toppingsButton.setBackground(new java.awt.Color(255, 255, 153));
        toppingsButton.setForeground(new java.awt.Color(255, 204, 102));
        toppingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mango.png"))); // NOI18N
        toppingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingsButtonActionPerformed(evt);
            }
        });

        toppingsButton1.setBackground(new java.awt.Color(255, 255, 153));
        toppingsButton1.setForeground(new java.awt.Color(255, 204, 102));
        toppingsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mango.png"))); // NOI18N
        toppingsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingsButton1ActionPerformed(evt);
            }
        });

        toppingsButton2.setBackground(new java.awt.Color(255, 255, 153));
        toppingsButton2.setForeground(new java.awt.Color(255, 204, 102));
        toppingsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mango.png"))); // NOI18N
        toppingsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingsButton2ActionPerformed(evt);
            }
        });

        toppingsButton3.setBackground(new java.awt.Color(255, 255, 153));
        toppingsButton3.setForeground(new java.awt.Color(255, 204, 102));
        toppingsButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mango.png"))); // NOI18N
        toppingsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingsButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppingsPanelLayout = new javax.swing.GroupLayout(toppingsPanel);
        toppingsPanel.setLayout(toppingsPanelLayout);
        toppingsPanelLayout.setHorizontalGroup(
            toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toppingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toppingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toppingsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toppingsButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toppingsPanelLayout.setVerticalGroup(
            toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppingsPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(toppingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toppingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toppingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toppingsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toppingsButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(sizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sizeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sizeButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toppingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel72)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productQuantityMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productQuantityPlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel73)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toppingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel74)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQuantityMinusBtn)
                    .addComponent(quantityLabel)
                    .addComponent(productQuantityPlusButton))
                .addGap(64, 64, 64)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productQuantityPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityPlusButtonActionPerformed
        quantity++;
        quantityLabel.setText(String.valueOf(quantity));
    }//GEN-LAST:event_productQuantityPlusButtonActionPerformed

    private void productQuantityMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityMinusBtnActionPerformed
        if (quantity > 1) quantity--;
        quantityLabel.setText(String.valueOf(quantity));
    }//GEN-LAST:event_productQuantityMinusBtnActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
    int unitPrice = BeaPOS.getProductPrice(productName, selectedSize); // if your "size" is your variant
    if (parent != null) {
        parent.addOrUpdateBillItem(productName, quantity, unitPrice, selectedSize, selectedToppings);
    }
    this.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void sizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeButtonActionPerformed
       selectedSize = sizeButton.getText();
    }//GEN-LAST:event_sizeButtonActionPerformed

    private void sizeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeButton2ActionPerformed
        selectedSize = sizeButton2.getText();
    }//GEN-LAST:event_sizeButton2ActionPerformed

    private void sizeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeButton3ActionPerformed
       selectedSize = sizeButton3.getText();
    }//GEN-LAST:event_sizeButton3ActionPerformed

    private void toppingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toppingsButtonActionPerformed
        selectedToppings = toppingsButton.getText();
    }//GEN-LAST:event_toppingsButtonActionPerformed

    private void toppingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toppingsButton1ActionPerformed
        selectedToppings = toppingsButton.getText();
    }//GEN-LAST:event_toppingsButton1ActionPerformed

    private void toppingsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toppingsButton2ActionPerformed
       selectedToppings = toppingsButton.getText();
    }//GEN-LAST:event_toppingsButton2ActionPerformed

    private void toppingsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toppingsButton3ActionPerformed
        selectedToppings = toppingsButton.getText();
    }//GEN-LAST:event_toppingsButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CancelButton;
    private javax.swing.JLabel ProductLabel;
    private javax.swing.JToggleButton doneButton;
    private javax.swing.JLabel imageOfProductLabel;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton productQuantityMinusBtn;
    private javax.swing.JButton productQuantityPlusButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JToggleButton sizeButton;
    private javax.swing.JToggleButton sizeButton2;
    private javax.swing.JToggleButton sizeButton3;
    private javax.swing.JToggleButton toppingsButton;
    private javax.swing.JToggleButton toppingsButton1;
    private javax.swing.JToggleButton toppingsButton2;
    private javax.swing.JToggleButton toppingsButton3;
    private javax.swing.JPanel toppingsPanel;
    // End of variables declaration//GEN-END:variables
}
